name = "multi-tenant-mail-clone"
type = "javascript"
main = "dist/index.js"
compatibility_date = "2025-01-31"
pages_build_output_dir = "dist"

[env.production]
name = "multi-tenant-mail-clone-production"

[build]
command = "npm run build"
cwd = "./"
watch_paths = []

[build.upload]
format = "plain"

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["**/*.js"]
fallthrough = true

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["**/*.css"]
fallthrough = true
